packages:
  - apps/*
  - packages/*
  - examples/*

allowBuilds:
  '@swc/core': true
  esbuild: true
  lefthook: true
  sharp: true
  unrs-resolver: true

catalog:
  '@eslint/js': ^9.39.1
  '@next/eslint-plugin-next': ^15.5.0
  '@types/node': ^25.2.0
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.24
  eslint-plugin-turbo: ^2.7.1
  globals: ^16.5.0
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver
