import { existsSync, readFileSync, writeFileSync } from "fs";
import { glob } from "glob";
import { join } from "path";
import { createUnplugin, type UnpluginInstance } from "unplugin";
import { resolveOptions, type Options } from "./core/options";
import { findClsCalls } from "./core/parser";
import { transformClsCalls } from "./core/transform";

const unplugin: UnpluginInstance<Options | undefined, false> = createUnplugin(
  (rawOptions = {}) => {
    const options = resolveOptions(rawOptions);

    // Track all classes found across all files for Tailwind v4 safelist
    const allClasses = new Set<string>();
    let scannedInitially = false;

    const name = "cls-extended";

    // Function to scan a file for cls() calls
    const scanFile = (filePath: string) => {
      try {
        if (!existsSync(filePath)) return;

        const code = readFileSync(filePath, "utf-8");
        if (!code.includes("cls(")) return;

        const clsCalls = findClsCalls(code);
        for (const call of clsCalls) {
          // Add base classes
          const baseClasses = call.baseClasses.split(/\s+/).filter(Boolean);
          baseClasses.forEach((cls) => allClasses.add(cls));

          // Add responsive classes with prefixes
          for (const [breakpoint, classes] of Object.entries(
            call.responsiveClasses,
          )) {
            const responsiveClasses = classes.split(/\s+/).filter(Boolean);
            responsiveClasses.forEach((cls) =>
              allClasses.add(`${breakpoint}:${cls}`),
            );
          }
        }
      } catch (error) {
        console.error(`[cls-extended] Error scanning ${filePath}:`, error);
      }
    };

    return {
      name,
      enforce: "pre", // Run before Tailwind

      // Vite-specific: Scan all files at startup
      vite: {
        async configResolved(config) {
          if (scannedInitially) return;
          scannedInitially = true;

          // Normalize root path for cross-platform compatibility
          const root = config.root.replace(/\\/g, "/");

          // Scan all source files for cls() calls
          const patterns = [
            `${root}/src/**/*.{ts,tsx,js,jsx}`,
            `${root}/app/**/*.{ts,tsx,js,jsx}`,
            `${root}/pages/**/*.{ts,tsx,js,jsx}`,
            `${root}/components/**/*.{ts,tsx,js,jsx}`,
          ];

          console.log("[cls-extended] Root:", root);
          console.log("[cls-extended] Scanning patterns:", patterns);

          let totalFiles = 0;
          for (const pattern of patterns) {
            try {
              const files = await glob(pattern, {
                absolute: true,
                windowsPathsNoEscape: true,
              });
              console.log(
                `[cls-extended] Pattern "${pattern}" found ${files.length} files`,
              );
              totalFiles += files.length;
              files.forEach(scanFile);
            } catch (error) {
              console.error(
                `[cls-extended] Pattern "${pattern}" error:`,
                error,
              );
            }
          }

          console.log(
            `[cls-extended] Scanned ${totalFiles} files, found ${allClasses.size} classes`,
          );

          // Write classes to a file that Tailwind can scan
          const safelistPath = join(config.root, ".cls-extended-safelist.html");
          const classArray = Array.from(allClasses);
          const safelistContent = `<!-- Auto-generated by cls-extended - DO NOT EDIT -->
<!-- This file helps Tailwind CSS v4 discover classes used in cls() calls -->
<div class="${classArray.join(" ")}"></div>
`;
          writeFileSync(safelistPath, safelistContent, "utf-8");
          console.log(
            `[cls-extended] Wrote ${classArray.length} classes to ${safelistPath}`,
          );
        },

        handleHotUpdate({ file, server }) {
          // Re-scan the updated file
          if (file.match(/\.(ts|tsx|js|jsx)$/)) {
            scanFile(file);

            // Rewrite the safelist file
            const safelistPath = join(
              server.config.root,
              ".cls-extended-safelist.html",
            );
            const classArray = Array.from(allClasses);
            const safelistContent = `<!-- Auto-generated by cls-extended - DO NOT EDIT -->
<!-- This file helps Tailwind CSS v4 discover classes used in cls() calls -->
<div class="${classArray.join(" ")}"></div>
`;
            writeFileSync(safelistPath, safelistContent, "utf-8");
          }
        },
      },

      transformInclude(id) {
        // Only transform JS/TS files for cls() calls
        const includePatterns = Array.isArray(options.include)
          ? options.include
          : [options.include];

        return includePatterns.some((pattern) => {
          if (typeof pattern === "string") {
            return id.includes(pattern);
          }
          if (pattern instanceof RegExp) {
            return pattern.test(id);
          }
          return false;
        });
      },

      transform(code, id) {
        // Handle JS/TS files - transform cls() calls and extract classes
        if (!code.includes("cls(")) {
          return null;
        }

        // Extract classes for Tailwind v4 safelist (in case file wasn't scanned initially)
        const clsCalls = findClsCalls(code);
        for (const call of clsCalls) {
          // Add base classes
          const baseClasses = call.baseClasses.split(/\s+/).filter(Boolean);
          baseClasses.forEach((cls) => allClasses.add(cls));

          // Add responsive classes with prefixes
          for (const [breakpoint, classes] of Object.entries(
            call.responsiveClasses,
          )) {
            const responsiveClasses = classes.split(/\s+/).filter(Boolean);
            responsiveClasses.forEach((cls) =>
              allClasses.add(`${breakpoint}:${cls}`),
            );
          }
        }

        // Perform transformation
        return transformClsCalls(code, id, options);
      },
    };
  },
);

export default unplugin;
export type { Options } from "./core/options";
